/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.post[_ngcontent-%COMP%]{\r\n    border-bottom: solid #c2c2c2 1px;\r\n    padding-bottom: 5px;\r\n}\r\n\r\n.listpost[_ngcontent-%COMP%]{\r\n    height: 50px;\r\n}\r\n.listname[_ngcontent-%COMP%]{\r\n}\r\n\r\n.listimg[_ngcontent-%COMP%]{\r\n\r\n}\r\n\r\n.listnumber[_ngcontent-%COMP%]{\r\n    margin:auto;\r\n}\r\n\r\n.btn[_ngcontent-%COMP%]{\r\n    font-size: 1em;\r\n    border:none;\r\n}\r\n.btn[_ngcontent-%COMP%]:hover{\r\n    background-color: #FFFFFF;\r\n    border: none;\r\n}\r\n.upvoted[_ngcontent-%COMP%]{\r\n    color: #005d5f;\r\n}\r\n.upvoted[_ngcontent-%COMP%]:hover{\r\n    color: #222222;\r\n}\r\n.unUpvoted[_ngcontent-%COMP%]{\r\n    color: #222222;\r\n}\r\n.unUpvoted[_ngcontent-%COMP%]:hover{\r\n    color: #005d5f;\r\n\r\n}\r\n\r\n.button[_ngcontent-%COMP%]{\r\n    border: none;\r\n    background-color: inherit;\r\n    color: #005d5f;\r\n}\r\n.button[_ngcontent-%COMP%]:hover{\r\n    text-decoration: underline;\r\n    color: darkcyan;\r\n}\r\na[_ngcontent-%COMP%]{\r\n    color: #005d5f;\r\n}\r\na[_ngcontent-%COMP%]:hover{\r\n    color: darkcyan;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcm9ieWQvRG9jdW1lbnRzL1NjaG9vbC9EaXRKYWFyL01FQU4vUFJPSkVDVC9hc3NldHMvYXBwL3Bvc3QvcG9zdExpc3RJdGVtLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvcm9ieWQvRG9jdW1lbnRzL1NjaG9vbC9EaXRKYWFyL01FQU4vUFJPSkVDVC9hc3NldHMvYXBwL3Bvc3QvcG9zdExpc3RJdGVtLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
