/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './comment.component.ngfactory';
import * as i2 from './comment.component';
import * as i3 from '../service/typeGebruiker.service';
import * as i4 from '../service/auth.service';
import * as i5 from '../service/comment.service';
import * as i6 from '@angular/common';
import * as i7 from './TopCommentList.component';
const styles_TopCommentsComponent:any[] = [''];
export const RenderType_TopCommentsComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_TopCommentsComponent,data:{}});
function View_TopCommentsComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-comment',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_CommentComponent_0,
      i1.RenderType_CommentComponent)),i0.ɵdid(1,114688,(null as any),0,i2.CommentComponent,
      [i3.TypeGebruikerService,i4.AuthService,i5.CommentService],{post:[0,'post'],
          thiscomment:[1,'thiscomment'],topcomment:[2,'topcomment'],comments:[3,'comments'],
          page:[4,'page']},(null as any))],(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.post;
    const currVal_1:any = (<any>_v.parent).context.$implicit;
    const currVal_2:any = true;
    const currVal_3:any = _co.comments;
    const currVal_4:any = _co.pagina;
    _ck(_v,1,0,currVal_0,currVal_1,currVal_2,currVal_3,currVal_4);
  },(null as any));
}
function View_TopCommentsComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵand(16777216,(null as any),
      (null as any),1,(null as any),View_TopCommentsComponent_2)),i0.ɵdid(3,16384,
      (null as any),0,i6.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},
      (null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n        ']))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.isTopComment;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_TopCommentsComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_TopCommentsComponent_1)),i0.ɵdid(2,
      802816,(null as any),0,i6.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
      {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n    ']))],
      (_ck,_v) => {
        var _co:i7.TopCommentsComponent = _v.component;
        const currVal_0:any = _co.comments;
        _ck(_v,2,0,currVal_0);
      },(null as any));
}
export function View_TopCommentsComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-topComments',
      ([] as any[]),(null as any),(null as any),(null as any),View_TopCommentsComponent_0,
      RenderType_TopCommentsComponent)),i0.ɵdid(1,114688,(null as any),0,i7.TopCommentsComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TopCommentsComponentNgFactory:i0.ComponentFactory<i7.TopCommentsComponent> = i0.ɵccf('app-topComments',
    i7.TopCommentsComponent,View_TopCommentsComponent_Host_0,{comments:'comments',
        post:'post',pagina:'pagina'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvcm9ieWQvRG9jdW1lbnRzL1NjaG9vbC9EaXRKYWFyL01FQU4vUFJPSkVDVC9hc3NldHMvYXBwL2NvbW1lbnQvVG9wQ29tbWVudExpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3JvYnlkL0RvY3VtZW50cy9TY2hvb2wvRGl0SmFhci9NRUFOL1BST0pFQ1QvYXNzZXRzL2FwcC9jb21tZW50L1RvcENvbW1lbnRMaXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3JvYnlkL0RvY3VtZW50cy9TY2hvb2wvRGl0SmFhci9NRUFOL1BST0pFQ1QvYXNzZXRzL2FwcC9jb21tZW50L1RvcENvbW1lbnRMaXN0LmNvbXBvbmVudC50cy5Ub3BDb21tZW50c0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvcm9ieWQvRG9jdW1lbnRzL1NjaG9vbC9EaXRKYWFyL01FQU4vUFJPSkVDVC9hc3NldHMvYXBwL2NvbW1lbnQvVG9wQ29tbWVudExpc3QuY29tcG9uZW50LnRzLlRvcENvbW1lbnRzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgKm5nRm9yPVwibGV0IGNvbW1lbnQgb2YgY29tbWVudHNcIj5cbiAgICAgICAgICAgIDxhcHAtY29tbWVudCBbdGhpc2NvbW1lbnRdPVwiY29tbWVudFwiIFtwb3N0XT1cInBvc3RcIiAqbmdJZj1cImNvbW1lbnQuaXNUb3BDb21tZW50XCIgW2NvbW1lbnRzXT1cImNvbW1lbnRzXCIgW3RvcGNvbW1lbnRdPVwidHJ1ZVwiIFtwYWdlXT1cInBhZ2luYVwiPjwvYXBwLWNvbW1lbnQ+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtdG9wQ29tbWVudHM+PC9hcHAtdG9wQ29tbWVudHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDRVk7TUFBQTtvQ0FBQSxVQUFBO01BQUE7VUFBQTtVQUFBOztJQUFxQztJQUF4QjtJQUF5RjtJQUF0QjtJQUEwQztJQUExSCxXQUFxQyxVQUF4QixVQUF5RixVQUF0QixVQUEwQyxTQUExSDs7OztvQkFESjtNQUFBLHdFQUFzQzthQUFBLHVDQUNsQztNQUFBLG1FQUFBO01BQUE7TUFBQSxlQUF3SjtJQUFyRztJQUFuRCxXQUFtRCxTQUFuRDs7OztvQkFGWixrREFDUTtNQUFBLGlGQUFBO01BQUE7TUFBQSx1Q0FFTTs7O1FBRkQ7UUFBTCxXQUFLLFNBQUw7Ozs7b0JDRFI7TUFBQTtxQ0FBQSxVQUFBO01BQUE7SUFBQTs7Ozs7In0=
