/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './navbar/navbar.component.ngfactory';
import * as i3 from './navbar/navbar.component';
import * as i4 from './service/auth.service';
import * as i5 from '@angular/router';
import * as i6 from './service/pagina.service';
import * as i7 from './errors/error.component.ngfactory';
import * as i8 from './errors/error.component';
import * as i9 from './errors/error.service';
import * as i10 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['    '])),(_l()(),i1.ɵeld(1,
      0,(null as any),(null as any),1,'app-navbar',([] as any[]),(null as any),(null as any),
      (null as any),i2.View_NavbarComponent_0,i2.RenderType_NavbarComponent)),i1.ɵdid(2,
      114688,(null as any),0,i3.NavbarComponent,[i4.AuthService,i5.Router,i6.PaginaService],
      (null as any),(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),
      i1.ɵeld(4,16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(5,212992,(null as any),0,i5.RouterOutlet,[i5.ChildrenOutletContexts,
          i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i1.ɵeld(7,0,(null as any),(null as any),1,'app-error',([] as any[]),
          (null as any),(null as any),(null as any),i7.View_ErrorComponent_0,i7.RenderType_ErrorComponent)),
      i1.ɵdid(8,114688,(null as any),0,i8.ErrorComponent,[i9.ErrorService],(null as any),
          (null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    _ck(_v,2,0);
    _ck(_v,5,0);
    _ck(_v,8,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i10.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i10.AppComponent> = i1.ɵccf('my-app',
    i10.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvUkRWL0Rlc2t0b3AvTWVhblByb2plY3QvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1JEVi9EZXNrdG9wL01lYW5Qcm9qZWN0L2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL1JEVi9EZXNrdG9wL01lYW5Qcm9qZWN0L2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvUkRWL0Rlc2t0b3AvTWVhblByb2plY3QvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIiAgICA8YXBwLW5hdmJhcj48L2FwcC1uYXZiYXI+XHJcbiAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbiAgICA8YXBwLWVycm9yPjwvYXBwLWVycm9yPlxyXG4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDRDQUFJO01BQUE7TUFBQSwrRUFBQTtNQUFBO01BQUEsNkJBQXlCLDhDQUN6QjthQUFBO1VBQUE7YUFBQTswREFBQTtVQUFBLDZCQUErQjtNQUMvQjtVQUFBO2FBQUE7VUFBQSxlQUF1QjtJQUZ2QjtJQUNBO0lBQ0E7Ozs7b0JDRko7TUFBQTthQUFBO1VBQUE7OzsifQ==
